/* charmonize.c -- write lucyconf.h config file.
 */

#include "Charmonizer/Core.h"
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include "Charmonizer.h"
#include "Charmonizer/FuncMacro.h"
#include "Charmonizer/Integers.h"
#include "Charmonizer/LargeFiles.h"
#include "Charmonizer/UnusedVars.h"
#include "Charmonizer/VariadicMacros.h"

/* Path to where the config file will be written.
 */
static char *outpath;

/* Process command line args, set up Charmonizer, etc. 
 */
static void
init(int argc, char **argv);

/* Assign the location where the config file will be written.
 */
static void 
set_outpath(char* path);

/* Start the config file.
 */
static void 
start_conf_file();

/* Write the last bit of the config file.
 */
static void 
finish_conf_file(FILE *fh);

/* Print a message to stderr and exit.
 */
void
die(char *format, ...);

int main(int argc, char **argv) 
{
    FILE *config_fh;

    /* parse commmand line args, init Charmonizer, open outfile */
    init(argc, argv);
    config_fh = fopen(outpath, "w");
    if (config_fh == NULL)
        die("Couldn't open '%s': %s", strerror(errno));
    start_conf_file(config_fh);

    /* modules section */
    chaz_FuncMacro_run(config_fh);
    chaz_Integers_run(config_fh);
    chaz_LargeFiles_run(config_fh);
    chaz_UnusedVars_run(config_fh);
    chaz_VariadicMacros_run(config_fh);

    /* write tail of config and clean up */
    finish_conf_file(config_fh);
    if (fclose(config_fh))
        die("Error closing file '%s': %s", outpath, strerror(errno));
    free(outpath);

    return 0;
}

static void 
init(int argc, char **argv) 
{
    int i;
    char *compiler;
    
    /* start seting up Charmonizer */
    chaz_set_prefixes("LUCY_", "Lucy_", "lucy_", "lucy_");

    compiler = NULL;
    outpath  = NULL;

    /* process command line args */
    for (i = 1; i < argc; i++) {
        if (strncmp(argv[i], "--cc=", 5) == 0) {
            compiler = argv[i] + 5;
        }
        else if (strncmp(argv[i], "--outpath=", 10) == 0) {
            outpath = strdup(argv[i] + 10);
        }
    }

    /* default to using "cc" to invoke the compiler */
    compiler = compiler == NULL ? "cc" : compiler;
    chaz_set_compiler(compiler);

    /* require an outpath */
    if (outpath == NULL)
        die("Usage: ./charmonize --outpath=OUTPATH [--cc=COMPILER]");
}

static void 
start_conf_file(FILE *conf_fh) 
{
    fprintf(conf_fh,
        "/* Header file auto-generated by Charmonizer. \n"
        " * DO NOT EDIT THIS FILE!!\n"
        " */\n\n"
        "#ifndef H_LUCY_CONF\n"
        "#define H_LUCY_CONF 1\n\n"
    );
}

static void
finish_conf_file(FILE *conf_fh) 
{
    fprintf(conf_fh,
        "/* conf end */\n"
        "#ifdef LUCY_USE_SHORT_NAMES\n"
        "# define bool_t                    lucy_bool_t\n"
        "# define i8_t                      lucy_i8_t\n"
        "# define u8_t                      lucy_u8_t\n"
        "# define i16_t                     lucy_i16_t\n"
        "# define u16_t                     lucy_u16_t\n"
        "# define i32_t                     lucy_i32_t\n"
        "# define u32_t                     lucy_u32_t\n"
        "# define i64_t                     lucy_i64_t\n"
        "# define u64_t                     lucy_u64_t\n"
        "# define Unused_Var(x)             Lucy_Unused_Var(x)\n"
        "# define Unreachable_Return(type)  Lucy_Unreachable_Return(type)\n"
        "# define FSeek                     lucy_FSeek\n"
        "# define FTell                     lucy_FTell\n"
        "#endif\n"
    );

    fprintf(conf_fh, 
        "\n\n#endif /* H_LUCY_CONF */\n\n"
    );
}

void 
die(char* format, ...) 
{
    va_list args;
    va_start(args, format);
    vfprintf(stderr, format, args);
    va_end(args);
    fprintf(stderr, "\n");
    exit(1);
}

/**
 * Copyright 2004 The Apache Software Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

